// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfujiqviruoymeuprsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZnVqaXF2aXJ1b3ltZXVwcnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzgxODksImV4cCI6MjA3MzYxNDE4OX0.kxEug-p7H3MDTHfXlwRo7tku4NZnRzZjk2PdrD8Kem8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});